drop table user if exists;
create table users (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  firstname varchar(50) not null,
  lastname varchar(50) not null,
  email varchar(50) not null,
  age integer not null
);
